export const TestOrder = [
    { id: 'Earpiece', route: 'EarpieceTest', title: 'Earpiece Test' },
    { id: 'Speaker', route: 'SpeakerTest', title: 'Speaker Test' },
    { id: 'Microphone', route: 'MicTest', title: 'Microphone Test' },
    { id: 'Camera', route: 'CameraTest', title: 'Camera Test' },
    { id: 'Video', route: 'VideoTest', title: 'Video Sync Test' },
    { id: 'Touch', route: 'TouchTest', title: 'Single Touch' },
    { id: 'MultiTouch', route: 'MultiTouchTest', title: 'Multi-Touch' },
    { id: 'Display', route: 'DisplayTest', title: 'Display Colors' },
    { id: 'Proximity', route: 'ProximityTest', title: 'Proximity Test' },
    { id: 'Vibration', route: 'VibrationTest', title: 'Vibration Test' },
    { id: 'Flash', route: 'FlashTest', title: 'Flash Test' },
    { id: 'GPS', route: 'GPSTest', title: 'GPS Test' },
    { id: 'Signal', route: 'NetworkTest', title: 'Signal Test' },
    { id: 'Fingerprint', route: 'FingerprintTest', title: 'Fingerprint Test' },
    { id: 'Face ID', route: 'FaceUnlockTest', title: 'Face ID Test' },
    { id: 'Wi-Fi', route: 'WifiTest', title: 'Wi-Fi Test' },
    { id: 'Bluetooth', route: 'BluetoothTest', title: 'Bluetooth Test' },
    { id: 'Sensors', route: 'SensorTest', title: 'Sensors Test' },
    { id: 'Battery', route: 'BatteryTest', title: 'Battery Test' },
    { id: 'NFC', route: 'NfcTest', title: 'NFC Test' },
    { id: 'Buttons', route: 'ButtonsTest', title: 'Buttons Test' },
    { id: 'Headset', route: 'HeadphoneJackTest', title: 'Headjack Test' },
];
